"use strict";

const guide = ({ why, intuition, steps, formula, parts, example, code, confusions, remember }) => ({
  why,
  intuition,
  steps,
  formula,
  parts,
  example,
  code,
  confusions,
  remember,
});

window.KNOWLEDGE_ENRICHMENT = {
  aliases: {
    "python-values": "python-values-types",
    "python-types": "python-values-types",
    "python-strings": "python-values-types",
    "numpy-arrays": "numpy-array-anatomy",
    "numpy-indexing": "numpy-vectorization-broadcasting",
    "numpy-vectorization": "numpy-vectorization-broadcasting",
    "numpy-statistics": "numpy-math-linear-algebra",
    "numpy-linear-algebra": "numpy-math-linear-algebra",
    "numpy-api-project": "numpy-api-health-project",
    "pandas-frames": "pandas-dataframes-indexing",
    "pandas-io": "pandas-dataframes-indexing",
    "pandas-selection": "pandas-dataframes-indexing",
    "pandas-dtypes": "pandas-cleaning-transform",
    "pandas-combine": "pandas-joins-aggregation",
    "pandas-aggregation": "pandas-joins-aggregation",
    "pandas-accessors": "pandas-cleaning-transform",
    matplotlib: "matplotlib-chart-grammar",
    seaborn: "seaborn-statistical-viz",
    plotly: "plotly-interactive-charts",
    "projection-3d": "plotly-3d-projection",
    "eda-widths": "iris-eda",
    "iris-visuals": "iris-eda",
    "categorical-encoding": "ml-preprocessing",
    "standard-scaling": "ml-preprocessing",
    "normalizer-binarizer": "ml-preprocessing",
    "safe-pipelines": "train-test-leakage",
    "features-labels": "sklearn-estimator-api",
    "train-test-split": "train-test-leakage",
    "estimator-api": "sklearn-estimator-api",
    "synthetic-data": "synthetic-datasets",
    "linear-regression": "linear-regression",
    "coef-intercept": "linear-regression",
    "multiple-regression": "multiple-linear-regression",
    "polynomial-regression": "polynomial-regression",
    ridge: "ridge-regression",
    lasso: "lasso-regression",
    "elastic-net": "elastic-net",
    "r-squared": "r-squared",
    "decision-tree-classification": "decision-tree-classification",
    "decision-tree-regression": "decision-tree-regression",
    "naive-bayes": "naive-bayes",
    "classification-metrics": "classification-metrics",
    "roc-auc": "roc-auc",
    kmeans: "kmeans-clustering",
    hierarchical: "hierarchical-clustering",
    dendrogram: "hierarchical-clustering",
    dbscan: "dbscan-clustering",
    "anomaly-workflow": "outlier-detection",
    "elliptic-envelope": "elliptic-envelope",
    "isolation-forest": "isolation-forest",
    "local-outlier-factor": "local-outlier-factor",
    "cross-validation": "cross-validation",
    "hyperparameter-search": "hyperparameter-tuning",
    "random-forest": "random-forest",
    adaboost: "adaboost",
    "gradient-boosting": "gradient-boosting",
    voting: "voting-ensemble",
    "random-forest-regression": "random-forest-regression",
    "streamlit-model": "streamlit-app-model",
    "streamlit-sales": "streamlit-app-model",
    "iris-project": "iris-eda",
    "attrition-pipeline": "train-test-leakage",
    "regression-practice-series": "linear-regression",
  },

  branchProfiles: {
    python: { icon: "PY", label: "Language layer", description: "Values and types are the vocabulary used by every data and model workflow.", route: ["Values", "Types", "Expressions", "Programs"] },
    math: { icon: "∑", label: "Reasoning layer", description: "Math explains what the libraries calculate and why model behavior changes.", route: ["Algebra", "Statistics", "Linear algebra", "Optimization"] },
    numpy: { icon: "NP", label: "Numerical layer", description: "Arrays turn formulas into fast, shape-aware computation.", route: ["Shape", "Selection", "Vectorization", "Linear algebra"] },
    pandas: { icon: "PD", label: "Data layer", description: "Labeled tables make raw records inspectable, cleanable, and comparable.", route: ["Load", "Inspect", "Transform", "Summarize"] },
    visualization: { icon: "◒", label: "Seeing layer", description: "Charts expose distribution, relationship, separation, and error before a metric hides them.", route: ["Static", "Statistical", "Interactive", "Exploratory"] },
    preparation: { icon: "FX", label: "Feature layer", description: "Preprocessing converts raw fields into model-ready evidence without leaking future information.", route: ["Audit", "Clean", "Transform", "Compose"] },
    workflow: { icon: "ML", label: "Method layer", description: "A repeatable workflow separates learning from honest evaluation.", route: ["Frame", "Split", "Fit", "Evaluate"] },
    regression: { icon: "ŷ", label: "Numeric prediction", description: "Regression learns a rule for a continuous target and measures the remaining distance.", route: ["Fit", "Regularize", "Optimize", "Measure"] },
    classification: { icon: "01", label: "Label prediction", description: "Classification learns a boundary and measures different kinds of correct and incorrect decisions.", route: ["Boundary", "Probability", "Decision", "Metrics"] },
    unsupervised: { icon: "◎", label: "Structure discovery", description: "Unsupervised methods reveal groups and unusual rows when no answer column is supplied.", route: ["Distance", "Density", "Groups", "Anomalies"] },
    selection: { icon: "CV", label: "Reliability layer", description: "Validation, tuning, and ensembles reduce dependence on one split or one model.", route: ["Resample", "Search", "Combine", "Verify"] },
    apps: { icon: "APP", label: "Applied layer", description: "Projects prove that separate lessons can cooperate inside one useful workflow.", route: ["Interact", "Analyze", "Explain", "Deliver"] },
  },

  groups: {
    python: [
      { title: "Language core", ids: ["python-values", "python-types", "python-strings"] },
    ],
    math: [
      { title: "Algebra & functions", ids: ["algebra-expressions", "functions-graphs"] },
      { title: "Descriptive statistics", ids: ["central-tendency", "spread-shape", "correlation"] },
      { title: "Probability & inference", ids: ["probability", "normal-zscore", "sampling-clt", "hypothesis-testing", "z-t-tests", "chi-square"] },
      { title: "Model mathematics", ids: ["linear-algebra", "calculus-gradient"] },
    ],
    numpy: [
      { title: "Array foundations", ids: ["numpy-arrays", "numpy-indexing", "numpy-vectorization"] },
      { title: "Numerical methods", ids: ["numpy-statistics", "numpy-linear-algebra"] },
      { title: "Applied practice", ids: ["numpy-api-project"] },
    ],
    pandas: [
      { title: "Table foundations", ids: ["pandas-frames", "pandas-io", "pandas-selection"] },
      { title: "Cleaning & transformation", ids: ["pandas-dtypes", "pandas-accessors"] },
      { title: "Combining & summarizing", ids: ["pandas-combine", "pandas-aggregation"] },
    ],
    visualization: [
      { title: "Plotting libraries", ids: ["matplotlib", "seaborn", "plotly", "projection-3d"] },
      { title: "Exploratory practice", ids: ["eda-widths", "iris-visuals", "pizza-visuals"] },
    ],
    preparation: [
      { title: "Data quality", ids: ["data-collection", "cleaning-strategy", "missing-values", "imputation", "duplicate-dtype", "outlier-iqr-zscore"] },
      { title: "Feature transformation", ids: ["categorical-encoding", "standard-scaling", "normalizer-binarizer", "distribution-transform", "feature-engineering"] },
      { title: "Training safeguards", ids: ["class-imbalance", "feature-selection", "safe-pipelines"] },
    ],
    workflow: [
      { title: "Problem & data", ids: ["ml-foundations", "features-labels", "synthetic-data"] },
      { title: "Estimator workflow", ids: ["train-test-split", "estimator-api"] },
    ],
    regression: [
      { title: "Linear family", ids: ["linear-regression", "coef-intercept", "multiple-regression", "polynomial-regression"] },
      { title: "Regularization", ids: ["ridge", "lasso", "elastic-net"] },
      { title: "Optimization & evaluation", ids: ["regression-errors", "gradient-descent", "mae", "mse-rmse", "r-squared"] },
    ],
    classification: [
      { title: "Tree & probability models", ids: ["classification-basics", "decision-tree-classification", "decision-tree-regression", "naive-bayes"] },
      { title: "Neighbor models", ids: ["knn-neighbors"] },
      { title: "Margin models", ids: ["svc-linear", "svc-kernels"] },
      { title: "Decision quality", ids: ["classification-metrics", "roc-auc"] },
    ],
    unsupervised: [
      { title: "Clustering", ids: ["kmeans", "hierarchical", "dendrogram", "dbscan"] },
      { title: "Anomaly detection", ids: ["anomaly-workflow", "elliptic-envelope", "isolation-forest", "local-outlier-factor"] },
    ],
    selection: [
      { title: "Validation & search", ids: ["cross-validation", "hyperparameter-search"] },
      { title: "Bagging & boosting", ids: ["random-forest", "adaboost", "gradient-boosting", "random-forest-regression"] },
      { title: "Model combination", ids: ["voting"] },
    ],
    apps: [
      { title: "Interactive applications", ids: ["streamlit-model", "streamlit-sales", "iris-project"] },
      { title: "Integrated practice", ids: ["attrition-pipeline", "regression-practice-series"] },
    ],
  },

  guides: {
    "algebra-expressions": guide({
      why: "ML formulas are algebraic programs: inputs enter an expression, parameters change their influence, and one output comes back.",
      intuition: "A chai stall profit formula is a tiny prediction model. Cups sold are the input, profit per cup is the weight, and fixed rent is the intercept.",
      steps: ["Name the changing quantity.", "Write the relationship as an expression.", "Substitute a real value.", "Rearrange the same equation when the unknown changes."],
      formula: "y = wx + b",
      parts: [{ term: "x", meaning: "input value" }, { term: "w", meaning: "rate or learned weight" }, { term: "b", meaning: "fixed starting value" }, { term: "y", meaning: "result" }],
      example: "If each cup earns ₹20 and daily fixed cost is ₹200, profit for 30 cups is 20 × 30 − 200 = ₹400.",
      confusions: ["A variable is not random by definition; it is simply allowed to change.", "The equals sign states a relationship, while Python's = performs assignment."],
      remember: "Translate the story into quantities before touching the equation.",
    }),
    "central-tendency": guide({
      why: "A single center value is useful for summaries and imputation, but the correct center depends on the data's shape.",
      intuition: "Mean shares the total equally, median chooses the middle person, and mode chooses the most common answer.",
      steps: ["Inspect the distribution.", "Calculate all three centers.", "Check whether outliers pull the mean.", "Choose the center that matches the question."],
      formula: "mean = Σx / n",
      parts: [{ term: "Σx", meaning: "sum of all observations" }, { term: "n", meaning: "number of observations" }],
      example: "For 10, 12, 13, 14, 100: the median is 13 while the mean is 29.8 because 100 pulls it upward.",
      confusions: ["Median requires sorting.", "Mode can be absent or have several answers.", "Mean is not always the best representative value."],
      remember: "Outliers pull the mean; the median stands its ground.",
    }),
    "spread-shape": guide({
      why: "Two columns can share the same mean but have completely different reliability, risk, and outlier behavior.",
      intuition: "Spread asks how tightly observations crowd around the center; skew asks which side has the long tail.",
      steps: ["Find the center.", "Measure distances from it.", "Summarize all distances with variance, standard deviation, or IQR.", "Inspect the distribution shape before choosing a method."],
      formula: "variance = Σ(x − μ)² / n",
      parts: [{ term: "x", meaning: "one observation" }, { term: "μ", meaning: "population mean" }, { term: "n", meaning: "population size" }],
      example: "The IQR ignores the lowest and highest quarters, so one extreme salary does not redefine the middle spread.",
      confusions: ["Variance is in squared units; standard deviation returns to the original unit.", "A large standard deviation is not automatically bad."],
      remember: "Center says where; spread says how far; skew says which direction.",
    }),
    probability: guide({
      why: "Many classifiers do not output certainty; they estimate how plausible each class is from available evidence.",
      intuition: "A spam word changes the probability of spam because it is new evidence, not because the word guarantees the answer.",
      steps: ["Define the event.", "Define the possible outcomes.", "Condition on known evidence when appropriate.", "Update the probability without treating it as certainty."],
      formula: "P(A|B) = P(A ∩ B) / P(B)",
      parts: [{ term: "A", meaning: "event we care about" }, { term: "B", meaning: "evidence already known" }],
      example: "P(spam | contains 'offer') asks how often messages are spam among messages that contain that word.",
      confusions: ["P(A|B) is usually not P(B|A).", "Probability 0.8 does not mean eight of the next ten individual cases must be positive."],
      remember: "Conditional probability narrows the world to cases where the evidence is true.",
    }),
    "normal-zscore": guide({
      why: "Z-scores make values from different scales comparable and support standardization and simple anomaly rules.",
      intuition: "Instead of saying a score is 92, say it is 1.7 standard deviations above its group's average.",
      steps: ["Find the column mean.", "Find its standard deviation.", "Subtract the mean from the value.", "Divide by the standard deviation."],
      formula: "z = (x − μ) / σ",
      parts: [{ term: "x", meaning: "raw value" }, { term: "μ", meaning: "mean" }, { term: "σ", meaning: "standard deviation" }],
      example: "If mean = 70, standard deviation = 10, and x = 90, then z = 2.",
      confusions: ["A Z-score rule assumes the distribution is suitable for that interpretation.", "Standardizing does not remove outliers."],
      remember: "A Z-score is a distance measured in standard deviations.",
    }),
    correlation: guide({
      why: "Correlation helps detect signal and redundant inputs before modeling, but it cannot establish cause.",
      intuition: "If two columns rise together, they move in the same direction; if one rises while the other falls, they move oppositely.",
      steps: ["Plot the two variables.", "Calculate Pearson r for a linear relationship.", "Read direction and magnitude.", "Investigate context and possible confounders."],
      formula: "r = cov(X,Y) / (σX σY)",
      parts: [{ term: "cov(X,Y)", meaning: "shared movement" }, { term: "σX, σY", meaning: "individual spreads" }],
      example: "r near +1 means a strong positive linear relationship; r near 0 only means little linear relationship.",
      confusions: ["Correlation is not causation.", "r near 0 can still hide a strong curved relationship."],
      remember: "Plot first; one coefficient cannot tell the whole relationship.",
    }),
    "hypothesis-testing": guide({
      why: "A statistical test separates an observed difference from the amount of variation expected by chance under a stated assumption.",
      intuition: "Begin by temporarily assuming nothing changed, then ask how surprising the observed result would be in that world.",
      steps: ["State H0 and H1.", "Choose alpha before looking at the result.", "Calculate the test statistic and p-value or critical boundary.", "Make a decision in the language of the original question."],
      formula: "decision: p ≤ α → reject H0",
      parts: [{ term: "p", meaning: "surprise under the null assumption" }, { term: "α", meaning: "pre-chosen error tolerance" }],
      example: "At α = 0.05, p = 0.02 is evidence against H0; it does not prove H1 with 98% probability.",
      confusions: ["Failing to reject H0 is not proving H0.", "Statistical significance is not practical importance."],
      remember: "The test answers a precise question only under its assumptions.",
    }),
    "linear-algebra": guide({
      why: "Most ML data and parameters are vectors and matrices; prediction is often a dot product repeated across rows.",
      intuition: "One customer is a feature vector. The full customer table is a matrix. A weight vector scores every customer's features.",
      steps: ["Check each object's shape.", "Align the inner dimensions.", "Multiply matching entries.", "Add them to form each dot product result."],
      formula: "ŷ = Xw + b",
      parts: [{ term: "X", meaning: "rows × features matrix" }, { term: "w", meaning: "one weight per feature" }, { term: "b", meaning: "intercept" }, { term: "ŷ", meaning: "predictions" }],
      example: "X shape (150,4) multiplied by w shape (4,) produces 150 scores.",
      confusions: ["Element-wise multiplication is not matrix multiplication.", "In NumPy eigenvectors returned by eig are stored as columns."],
      remember: "For A(m×n) @ B(n×p), the inner n values must match.",
    }),
    "missing-values": guide({
      why: "Missing values can silently remove rows, break estimators, or bias results if the reason for missingness is ignored.",
      intuition: "A blank credit score is not automatically zero; it is an unknown whose treatment depends on why it is missing.",
      steps: ["Count missing values by column.", "Convert counts to percentages.", "Investigate why values are missing.", "Drop, flag, or fill using a documented rule.", "Compare the distribution before and after."],
      code: "missing_pct = df.isna().mean().mul(100)\nclean = df.dropna(subset=[\"target\"])\nclean[\"income\"] = clean[\"income\"].fillna(clean[\"income\"].median())",
      confusions: ["Missing does not mean zero.", "A global mean can be wrong for categories or ordered data.", "Blind dropna can discard a large fraction of the dataset."],
      remember: "Measure first, understand second, modify last.",
    }),
    imputation: guide({
      why: "Imputation keeps usable rows while making the replacement rule repeatable for future data.",
      intuition: "SimpleImputer uses one learned column rule; KNNImputer borrows information from rows with similar known features.",
      steps: ["Split train and test.", "Fit the imputer on training columns only.", "Transform both train and test with the same learned rule.", "Keep a missingness indicator when absence itself may carry signal."],
      code: "imputer = SimpleImputer(strategy=\"median\")\nX_train_ready = imputer.fit_transform(X_train)\nX_test_ready = imputer.transform(X_test)",
      confusions: ["fit_transform on the complete dataset leaks test information.", "A numerically valid replacement can still be semantically wrong."],
      remember: "The test set may receive the rule; it must never teach the rule.",
    }),
    "class-imbalance": guide({
      why: "When one class dominates, a model can achieve high accuracy by ignoring the rare class that matters most.",
      intuition: "If only 1 in 100 transactions is fraud, predicting 'not fraud' every time is 99% accurate and completely useless.",
      steps: ["Inspect target counts.", "Choose metrics that expose minority performance.", "Resample training folds only.", "Compare against class weights and threshold changes."],
      formula: "accuracy = correct / all rows",
      example: "99 correct majority guesses and 1 missed fraud still produce 99% accuracy but 0% fraud recall.",
      confusions: ["Never resample before splitting.", "Oversampling changes the training distribution, not the real-world prevalence."],
      remember: "Ask which class errors matter before choosing a metric or sampler.",
    }),
    "feature-engineering": guide({
      why: "A model can only use relationships represented in its input columns; useful derived features can expose structure the raw columns hide.",
      intuition: "Length and width may be weak alone, while area = length × width directly represents the physical relationship.",
      steps: ["Start from a domain relationship.", "Create the feature using training-safe logic.", "Inspect scale and missing behavior.", "Measure whether validation improves."],
      code: "df[\"area\"] = df[\"length\"] * df[\"width\"]\ndf[\"income_per_person\"] = df[\"income\"] / df[\"household_size\"]\ndf[\"month\"] = df[\"date\"].dt.month",
      confusions: ["More columns do not automatically improve a model.", "A feature derived from future information is target leakage."],
      remember: "A useful feature expresses a real relationship, not just another calculation.",
    }),
    "feature-selection": guide({
      why: "Removing weak or redundant inputs can simplify a model, reduce noise, and make validation more stable.",
      intuition: "A hiring panel does not need ten copies of the same question or a column that never changes.",
      steps: ["Remove constant or near-constant columns.", "Measure univariate signal when appropriate.", "Try wrapper selection inside cross-validation.", "Compare the smaller model on held-out data."],
      code: "selector = VarianceThreshold(threshold=0.01)\nX_reduced = selector.fit_transform(X_train)",
      confusions: ["Selection must be fitted inside the training process.", "A low linear correlation does not mean a feature has no nonlinear value."],
      remember: "The goal is not fewer columns; it is the smallest reliable evidence set.",
    }),
    "regression-errors": guide({
      why: "Training needs one number that says which candidate model is better, and evaluation needs metrics whose tradeoffs match the problem.",
      intuition: "Residuals are the individual misses; the cost function is the scoreboard across all misses.",
      steps: ["Predict every row.", "Calculate each residual.", "Transform residuals according to MAE or MSE.", "Aggregate and compare candidates."],
      formula: "residualᵢ = yᵢ − ŷᵢ",
      parts: [{ term: "yᵢ", meaning: "actual target" }, { term: "ŷᵢ", meaning: "predicted target" }],
      confusions: ["Loss can describe one row while cost summarizes many rows.", "Signed residuals can cancel if added directly."],
      remember: "The metric defines what kind of mistake the model is encouraged to avoid.",
    }),
    "gradient-descent": guide({
      why: "When a closed-form answer is unavailable or too expensive, gradients provide a direction for iterative improvement.",
      intuition: "On a dark hill, the local slope tells you which way is down; the learning rate controls how large a step you take.",
      steps: ["Start with parameter values.", "Predict and calculate cost.", "Calculate each derivative.", "Move parameters opposite the gradient.", "Repeat until improvement stabilizes."],
      formula: "wₙₑw = wₒₗd − η · ∂J/∂w",
      parts: [{ term: "η", meaning: "learning rate" }, { term: "J", meaning: "cost function" }, { term: "∂J/∂w", meaning: "local cost slope" }],
      confusions: ["A large learning rate can jump past the minimum.", "A tiny learning rate may appear stuck.", "The derivative supplies direction and steepness, not the final answer."],
      remember: "Measure the slope, step against it, and recalculate.",
    }),
    mae: guide({
      why: "MAE keeps error in original units and does not let a few large misses dominate as strongly as squared error.",
      intuition: "Measure the absolute vertical gap from every point to the prediction line, then average those lengths.",
      steps: ["Calculate actual minus predicted.", "Take the absolute value.", "Add all absolute errors.", "Divide by the row count."],
      formula: "MAE = Σ|y − ŷ| / n",
      example: "Errors −2, +3, −1 become 2, 3, 1, so MAE = 2.",
      confusions: ["MAE does not show error direction.", "Its sharp corner at zero is less convenient for gradient methods."],
      remember: "MAE is the average miss in the target's own unit.",
    }),
    "mse-rmse": guide({
      why: "MSE strongly penalizes large misses; RMSE preserves that behavior while returning the score to the target's unit.",
      intuition: "Squaring turns one very large error into a much larger warning signal.",
      steps: ["Calculate residuals.", "Square each residual.", "Average the squares for MSE.", "Take the square root for RMSE."],
      formula: "RMSE = √(Σ(y − ŷ)² / n)",
      example: "Errors 1 and 5 give MAE 3, but RMSE √13 ≈ 3.61 because the error of 5 receives extra weight.",
      confusions: ["MSE is in squared units.", "RMSE is not always better; its outlier sensitivity is a policy choice."],
      remember: "Square to emphasize large misses; root to recover readable units.",
    }),
    "svc-linear": guide({
      why: "SVC creates a class boundary with a margin designed to remain useful on unseen points, especially when the classes are separable in feature space.",
      intuition: "Place the widest possible road between two neighborhoods; the houses touching the road edges are the support vectors.",
      steps: ["Scale comparable numeric features.", "Fit a linear SVC on training rows.", "Locate the closest points that define the margin.", "Predict by checking which side of the boundary a new row falls on.", "Evaluate on enough held-out rows."],
      formula: "decision(x) = w·x + b",
      parts: [{ term: "w", meaning: "boundary orientation" }, { term: "b", meaning: "boundary offset" }, { term: "sign", meaning: "predicted side/class" }],
      code: "model = SVC(kernel=\"linear\", C=1.0)\nmodel.fit(X_train, y_train)\ny_pred = model.predict(X_test)",
      confusions: ["Support vectors are training rows, not invented boundary points.", "A two-row test set cannot support a strong accuracy conclusion.", "Unscaled features can distort the margin."],
      remember: "The nearest training points define the widest useful separating margin.",
    }),
    "knn-neighbors": guide({
      why: "KNN is a direct way to turn similarity into prediction and makes the effects of distance, scaling, and neighborhood size visible.",
      intuition: "Ask the closest known examples. For classification they vote for a label; for regression their target values are averaged.",
      steps: ["Place the new point in the same feature space as the training rows.", "Calculate its distance to each stored row.", "Select the k smallest distances.", "Use majority vote for classification or mean target for regression.", "Evaluate on held-out rows and tune k with cross-validation."],
      formula: "d(x,z) = √Σⱼ(xⱼ − zⱼ)²",
      parts: [{ term: "x,z", meaning: "two feature vectors" }, { term: "j", meaning: "one feature dimension" }, { term: "k", meaning: "number of neighbors used for prediction" }],
      example: "The notebook's regressor finds three neighbors for x = 1 and averages targets 81.98, 51.59, and 62.51 to reproduce the prediction.",
      code: "model = KNeighborsClassifier(n_neighbors=5)\nmodel.fit(X_train, y_train)\ny_pred = model.predict(X_test)\ndistances, indices = model.kneighbors([[-5, 0]])",
      confusions: ["KNN is distance-sensitive, so features on larger numeric scales can dominate.", "Calling score on all rows after fitting includes training rows and is not an honest test score.", "A very small k is noisy; a very large k can wash out local structure."],
      remember: "Scale first, choose k with validation, and evaluate on rows the model did not store during fitting.",
    }),
    "svc-kernels": guide({
      why: "Kernels let a linear separator act in a transformed feature space where a curved pattern may become separable.",
      intuition: "A circular boundary is difficult on flat paper; lifting points by x² + y² can turn inside versus outside into a height cut.",
      steps: ["Plot the raw feature space.", "Fit a linear baseline.", "Either add polynomial features or choose a polynomial/RBF kernel.", "Tune C and kernel settings inside cross-validation.", "Interpret the boundary back in the original view."],
      formula: "K(x,z) = (γ x·z + c₀)ᵈ",
      parts: [{ term: "γ", meaning: "feature influence scale" }, { term: "c₀", meaning: "constant offset" }, { term: "d", meaning: "polynomial degree" }],
      code: "model = SVC(kernel=\"poly\", degree=2, C=1.0)\nmodel.fit(X_train_raw, y_train)\nscore = model.score(X_test_raw, y_test)",
      confusions: ["A 3D chart is not automatically a three-feature model.", "Manual polynomial features and a polynomial kernel are related but not identical by default.", "The target Y must never become an input axis during training."],
      remember: "A kernel changes how rows are compared; it does not add visible columns to your DataFrame.",
    }),
  },
};
