// Transcribes an mp3 (e.g. one generated by generate-audio.mjs) into
// word-level captions using local Whisper.cpp — free, no API permissions
// needed (this is the fallback since the ElevenLabs key on this account
// lacks the speech_to_text scope).
// Usage: node scripts/caption-audio.mjs public/audio/test_hook.mp3
import { execSync } from "node:child_process";
import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "path";
import {
  WHISPER_LANG,
  WHISPER_MODEL,
  WHISPER_PATH,
  WHISPER_VERSION,
} from "../whisper-config.mjs";
import {
  downloadWhisperModel,
  installWhisperCpp,
  transcribe,
  toCaptions,
} from "@remotion/install-whisper-cpp";

const [, , mp3Arg] = process.argv;
if (!mp3Arg) {
  console.error("Usage: node scripts/caption-audio.mjs <path-to-mp3>");
  process.exit(1);
}

const mp3Path = path.resolve(mp3Arg);
const jsonPath = mp3Path.replace(/\.mp3$/, ".json");

await installWhisperCpp({ to: WHISPER_PATH, version: WHISPER_VERSION });
await downloadWhisperModel({ folder: WHISPER_PATH, model: WHISPER_MODEL });

const tempDir = path.join(process.cwd(), "temp");
let removeTempDir = false;
if (!existsSync(tempDir)) {
  mkdirSync(tempDir);
  removeTempDir = true;
}
const wavPath = path.join(tempDir, path.basename(mp3Path).replace(/\.mp3$/, ".wav"));

console.log("Converting to 16kHz wav...");
execSync(`npx remotion ffmpeg -i "${mp3Path}" -ar 16000 "${wavPath}" -y`, {
  stdio: ["ignore", "inherit"],
});

console.log("Transcribing with Whisper.cpp...");
const whisperCppOutput = await transcribe({
  inputPath: wavPath,
  model: WHISPER_MODEL,
  tokenLevelTimestamps: true,
  whisperPath: WHISPER_PATH,
  whisperCppVersion: WHISPER_VERSION,
  printOutput: false,
  translateToEnglish: false,
  language: WHISPER_LANG,
  splitOnWord: true,
});

const { captions } = toCaptions({ whisperCppOutput });
writeFileSync(jsonPath, JSON.stringify(captions, null, 2));
console.log(`Saved captions -> ${jsonPath}`);

if (removeTempDir) {
  rmSync(tempDir, { recursive: true });
}
